# Generated by Django 5.2.7 on 2026-05-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='parent_goal',
        ),
    ]
