# Generated by Django 5.2.7 on 2026-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_goal_parent_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actual_minutes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dayentry',
            name='dedication_minutes',
        ),
        migrations.RemoveField(
            model_name='dayentry',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='dayentry',
            name='reflection_text',
        ),
        migrations.RemoveField(
            model_name='dayentry',
            name='result_text',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_value',
        ),
        migrations.AddField(
            model_name='goal',
            name='target_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='planned', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
